[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c2195d0d30ae0faa4b7a8d30d2a12efe2125a50"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "b55c067aedd2abd4c489e472b93b8559c574009d87e73b24304699b0ef5cc69b"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68e5007d6d5fad1c939baf4d1d3460f8d7e98fd7"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "2206fb1a42ee6910aac18890efff15924dc7c0195fcd36670ce25579890c4660"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "858ec3ffc7821a9a736275eadd0e570ecd18456c"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "2e27e5b048bd54518f0639c4dd601f7346bb486f0c0b6fc695f55d7021ab8c96"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "968190f446ccbd9b085cb187ed3dd4026afc35a5"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "b2b14c7e1fc80477727c52ae6156adaf3a72fcf63063b192225c468cbb4c9419"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dfc5af4b33aed2fd200c95639a24dc960b94486"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "4bbdf8d1dc3c34a7d4b48bfad3d7a86c0c9c6786cefaf143a485d364076cd489"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c2b6cacc4f645a38db82ef37d6a712f97f3f739"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "15cc225bad4fa8a251fd5bb2d4f7f9e0a0b83d86a4b5b288a802ab40df6b6b41"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "607fe5d00a87242f7010341d797c7682e3ebb76b"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "748e6d47596672ca203bd8c735a870e065d469afdead6f1768978c5d6cd013c5"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "a723180d0b623edf4a04919c97ca6d18d6aaf014"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "85b31cb8f14b24b37195d57745cfaeae5d81094266be1ae025470f45fdd99e6a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2dcb00d6dc11dcb690fd9b6f0921daf692448ed"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "f1105c133e2f9e3cb33a9ab613bdd6383cf036dcc746b2daaefe719a36f252e7"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2403e076d02d20e71f8f48f049b7e887bfc191a9"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "b6ab5ff839c94779cf2b7c2e16cca4d8a0e60dd48c3e91febc1d8c8f262050d8"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c73687f6ffd441048c6d8ee8f815e490f1c337a1"
gpu = "cuda"
gpu_version = "13.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "93a4cf81672636575511e584c5db6b711502a666c58b6bd95e8e36a573cd14fb"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-linux-gnu-cxx11-gpu_version+13.1-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df91f89fb4473eb285fa2aab97941a32b99951eb"
gpu = "cuda"
gpu_version = "13.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "8a4535578af2f45d012e9556ab341ec1c40b5286da058b9c717715eac5577fc3"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.aarch64-linux-gnu-cxx11-gpu_version+13.1-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8c9ae2ba92d5d8bc93d511afddd5f2a98f1fbd2"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "b7657a0fb603a6e377e5fe5607aeb1c11687562fe08c7e11b16e93927200c755"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.358+0/Reactant.v0.0.358.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
