[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53a146cb057688d95d75c6289ccc16a4fa65c2eb"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "ac64313562f8fc614977a5225c40cc808ada8c5b243b4e388109e6f110974aba"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "509651e247eca37c16870b35ea9733e600a658d0"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "91babeed731a72a3b01e593301eee13316060bedd4ebe19d029dcb6e6e2e42cb"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "ff314b3981fe029816fabdc08b93b6e15f07f2d9"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "706a608f90f1cae85488f92780ad5b8b6101138677e10b4771f95d76bcbb5f35"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "28af1717c243d9b08d21602d0cdbcab3481e43db"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "882cf165cf740659525f49de724aeeec3e192a5bf4df4f1a3dba5b75bb058abc"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58d2fb124bf8e2b8c3888bc98dcce329f4111b11"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "53974ec7d818f9764c721dec82142c0ed98dc0e79c98dafc202598d0c8a37187"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cc2b724deab517e70b47a6df30ddbeb535cdc87"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "10e5f1933b6d7f2c55918dccd6b650ffc9f1a3aa70daecf5070bb3703c10f6e0"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "f4f8c146c46a9f33abcacfd94f854471d21d6615"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "88a4dddc06c64c515d3641c0972b628e8d28c54916a854a6b66f4ce6c16ddf93"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "cf022fbc6b5888d79b6ebb845500fbce927f09af"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "d3412b72f9fff0e564a31b546cea44a51a8413d1c2529839251afb088659ec61"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abd10dc42aeb0c536e81f07b1cf681ec28b1ab7c"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "ccef32402809230bf1800a3dac7253cea4d6a078e43353df14cc417ac6a567bd"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6be3b9d5e926c5832f7e33a6d7f3ec9cb0f34683"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "a7bef112d7758bb279f9ef4178acf1691b710f8a105ec699cd9830da4974e9fd"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b87493ee1cef0aabc0852ea869923aeae645c38"
gpu = "cuda"
gpu_version = "13.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "e7f149128e7d55a9a2488fe50bef6bda205c5b5e6ff2dda9e4043da0cbef70f2"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-linux-gnu-cxx11-gpu_version+13.1-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad0dd2414643699b886758d7a02e9c9b57206d8e"
gpu = "cuda"
gpu_version = "13.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "fea3f67df79984517e6848697ff7ae6fdbb95582254734e6cb5a029fd23ff955"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.aarch64-linux-gnu-cxx11-gpu_version+13.1-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a53c11d4133916acc00eeab4c59cb9601f2d0de9"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "46827c44f14a4613edd3b8761606cfea963ba87ab990d808dc20835f713aa616"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.350+0/Reactant.v0.0.350.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
