# Autogenerated wrapper script for Reactant_jll for aarch64-linux-gnu-cxx11-gpu_version+13.1-gpu+cuda-mode+opt
export fatbinary, libReactantExtra, libdevice, libnccl, ptxas

JLLWrappers.@generate_wrapper_header("Reactant")
JLLWrappers.@declare_library_product(libReactantExtra, "libReactantExtra.so")
JLLWrappers.@declare_executable_product(fatbinary)
JLLWrappers.@declare_file_product(libdevice)
JLLWrappers.@declare_library_product(libnccl, "libnccl.so.2")
JLLWrappers.@declare_executable_product(ptxas)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libReactantExtra,
        "lib/libReactantExtra.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        fatbinary,
        "lib/cuda/bin/fatbinary",
    )

    JLLWrappers.@init_file_product(
        libdevice,
        "lib/cuda/nvvm/libdevice/libdevice.10.bc",
    )

    JLLWrappers.@init_library_product(
        libnccl,
        "lib/libnccl.so.2",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        ptxas,
        "lib/cuda/bin/ptxas",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
